# Generated by Django 5.1.7 on 2025-04-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechaevento',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Teatro', 'Teatro'), ('Cine', 'Cine'), ('Exposición', 'Exposición')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cantidad_entradas', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.evento')),
                ('fecha_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.fechaevento')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
